---
- name: "Provide full sudo rights for ansible-ravi user"
  lineinfile:
    path: /etc/sudoers.d/ansible-ravi
    create: yes
    owner: root
    group: root
    mode: 0440
    line: 'ansible-ravi ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: /usr/sbin/visudo -cf %s
  register: sudo_result
