---
- name: "Include OS specific packages"
  include_vars: "{{ ansible_distribution }}_packages.yml" 

- name: "Install base packages on Ubuntu family systems"
  apt:
    name: "{{ base_packages }}"
    state: latest
  when: ansible_distribution == "Ubuntu"
